
let t_highlight_boolean=1
let t_highlight_types=1
let t_highlight_more_types=1
let t_highlight_debug=1
set background=dark
syntax enable
" fix
set expandtab 
set tabstop=2
set shiftwidth=2
set softtabstop=2
set autoindent
set smartindent
" end fix
set nocompatible
set modelines=0
set scrolloff=3
set showmode
set showcmd
set hidden
set visualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2

let mapleader=","

nnoremap / /
vnoremap / /

set ignorecase
set smartcase
" set gdefault 

set incsearch
set showmatch
set hlsearch

nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

set wrap
set linebreak
set nolist 
set textwidth=0
set wrapmargin=0
set formatoptions=qrn1

nnoremap j gj
nnoremap k gk

inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

nnoremap ; :

inoremap jj <ESC>
inoremap {{ {<cr>}<ESC>O<tab>
inoremap (( ()<ESC>i

au FocusLost * :wa

let @q='yyp2xwhc$=yjj'

nnoremap <leader>W :%s/+$//<cr>:let @/=''<CR>
nnoremap <leader>ft Vatzf
nnoremap <leader>q gqip
nnoremap <leader>v V`]

nnoremap <leader>cs :ConqueTermSplit 
nnoremap <leader>cvs :ConqueTermVSplit 

nnoremap <leader>ev <C-w><C-v><C-l>:e $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

nnoremap <leader>w <C-w>v<C-w>l
nnoremap <leader>nt :tabn<cr>
nnoremap <leader>pt :tabp<cr>

nnoremap <leader>ts /\s\+$<cr>

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-j>h
nnoremap <C-k> <C-k>h
nnoremap <C-l> <C-l>h

filetype plugin on
filetype indent on
