set nocompatible

execute pathogen#infect()

" NERDTree
map <C-n> :NERDTreeToggle<cr>

if has("autocmd")
  filetype on
  filetype plugin on
  filetype indent on

  " NERDTree
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
endif

let t_highlight_boolean=1
let t_highlight_types=1
let t_highlight_more_types=1
let t_highlight_debug=1

set background=dark

syntax enable
" fix
set tabstop=4
set shiftwidth=4
set shiftround
set softtabstop=4
set smarttab

set autoindent
set smartindent
" end fix

set modelines=0
set scrolloff=3

" Visual stuff
set showmode
set showcmd
set cursorline
set ruler
set visualbell
set noerrorbells
set incsearch
set showmatch
set hlsearch
set laststatus=2
set lazyredraw

set hidden
set ttyfast
set backspace=indent,eol,start

" Increase history
set history=1000
set undolevels=1000

set wildmenu
" Ignore some stuff for wildcards
set wildignore=*.sw[nop],*.bak,*.pyc,*.class,*.o,*.ali

" Handle screwy filetype mappings
au BufNewFile,BufRead *.cls set filetype=tex

" No backups or swapfiles
set nobackup
set noswapfile

" Toggle paste mode
set pastetoggle=<F2>

let mapleader=","

nnoremap / /
vnoremap / /

set ignorecase
set smartcase

nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

set wrap
set linebreak
set nolist
set textwidth=0
set wrapmargin=0
set formatoptions=qrn1

nnoremap j gj
nnoremap k gk

inoremap <f1> <esc>
nnoremap <f1> <esc>
vnoremap <f1> <esc>

" make < > shifts keep selection
vnoremap < <gv
vnoremap > >gv

" Sane command entry and escape
nnoremap ; :
inoremap jj <esc>

" Auto insert closing paren/brace/bracket on double tap
inoremap (( ()<esc>i
inoremap {{ <space>{<cr>}<esc>O
inoremap [[ []<esc>i
" Auto insert semicolon and nl on double tap
inoremap ;; <esc>A;<cr>

" Autosave when losing focus (gvim)
au FocusLost * :wa

" Search for trailing whitespace
nnoremap <leader>ts /\s\+$<cr>
" Strip all trailing whitespace in file
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>

" Ada/VHDL comment selected block
let @c=":s/^/--/g:noh"
let @v=":s@^@//@g:noh"

" Fold tag
nnoremap <leader>ft Vatzf

" Reformat paragraph
nnoremap <leader>q gqip

" Reselect recently pasted block
nnoremap <leader>v V`]

" Edit / Source vimrc
nnoremap <leader>ev <C-w><C-v><C-l>:e $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Open vertical split and switch to it
nnoremap <leader>w <C-w>v<C-w>l

" Tab navigation
nnoremap <leader>nt :tabn<cr>
nnoremap <leader>pt :tabp<cr>

" Window nav
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-j>h
nnoremap <C-k> <C-k>h
nnoremap <C-l> <C-l>h

" always show the git gutter
let g:gitgutter_sign_column_always = 1
" Sort out gutter colours
highlight clear SignColumn

